debug: true
branches:
  - "master"
  - name: "dev"
    channel: "rc"
    prerelease: "rc"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/github"
    - assets:
        - "CHANGELOG.md"
  - - "@semantic-release/exec"
    - prepareCmd: |
        ./mvnw -B license:format
      publishCmd: |
        ./mvnw -B clean license:check
  - - "@semantic-release/git"
    - assets: "."
