name: Gitflow
on:
  push:
    branches:
      - rc

jobs:
  build:
    name: Create release PR
    runs-on: ubuntu-latest
    steps:
      - uses: Logerfo/gitflow-action@0.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release: rc # The `release` branch.
          master: master # The `master` branch.
          label: release # The pull request label.
          auto-merge: false # If `true`, will try to automatically merge pull requests.
