name: Gitflow
on:
  push:
    branches:
      - rc

jobs:
  build:
    name: Gitflow
    runs-on: ubuntu-latest
    steps:
      - uses: Logerfo/gitflow-action@0.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # The `GITHUB_TOKEN` secret.
          release: rc # The `release` branch.
          master: master # The `master` branch.
          label: gitflow # The pull request label.
          auto-merge: false # If `true`, will try to automatically merge pull requests. Can also be set to `pull_request_review`, `check_run`, `push`, or a comma-separated combination of these values to only merge when handling the named events.
          require-merge: false # If an attempted merge fails, the action is considered to have failed.
