---
# see https://github.com/Logerfo/gitflow-action
name: Gitflow
on:
  push:
    branches:
      - rc
      - master

jobs:
  gitflow:
    name: 🔨 Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Debug action
        uses: hmarr/debug-action@v2.0.1
      - name: Debug echo
        env:
          GITHUB_CONTENT: "${{ toJson(github) }}"
          JOB_CONTENT: "${{ toJson(job) }}"
          STEPS_CONTENT: "${{ toJson(steps) }}"
        run: |
          echo $CONTENT
          echo $JOB_CONTENT
          echo $STEPS_CONTENT

      - uses: Logerfo/gitflow-action@0.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release: rc
          master: master
          dev: develop
          auto-merge: false
