name: Release

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # fix https://github.com/cycjimmy/semantic-release-action/issues/79
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: chmod u+x ./mvnw

      - name: Action For Semantic Release
        uses: cycjimmy/semantic-release-action@v2.7.0
        id: semantic
        with:
          semantic_version: 19
          extra_plugins: |
            @semantic-release/changelog
            @conveyal/maven-semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #      - name: Setup Node.js with GitHub Package Registry
      #        uses: actions/setup-node@v2
      #        with:
      #          node-version: 14
      #          registry-url: 'https://npm.pkg.github.com'
      #          scope: 'cycjimmy'
      #
      #      - name: Publish To GitHub Package Registry
      #        if: steps.semantic.outputs.new_release_published == 'true'
      #        run: npm publish
      #        env:
      #          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #
      #      - name: Push updates to branch for major version
      #        if: steps.semantic.outputs.new_release_published == 'true'
      #        run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v${{steps.semantic.outputs.new_release_major_version}}"
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
