---
name: "Verify PR"

on:
  workflow_call:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

jobs:
  build:
    name: Run tests & build
    runs-on: ubuntu-latest
    steps:
      - name: Debug action
        uses: hmarr/debug-action@v2.0.1
      - name: Debug echo
        env:
          JOB_CONTENT: "${{ toJson(job) }}"
          STEPS_CONTENT: "${{ toJson(steps) }}"
          GITHUB_CONTENT: "${{ toJson(github) }}"
        run: "echo 'Debug echo'"

      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: init jvm
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - run: ./mvnw -B clean package

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "target/surefire-reports/TEST-*.xml"
